/run/verbose 1
#/event/verbose 1
/tracking/verbose 1

/g4simple/setRandomSeed true
#/random/setSeed 12345678

# Need to set the physics list before we can do some of the other commands. 
/g4simple/setReferencePhysList Shielding

# Set GDML file name
# The bool after the file name turns validation on / off
/g4simple/setDetectorGDML detector.gdml 

# Set up output. Choose a format:
#/g4simple/setOutputFormat csv
#/g4simple/setOutputFormat xml
/g4simple/setOutputFormat root
#/g4simple/setOutputFormat hdf5

# Uncomment to override an output's standard option
#/g4simple/setOutputOption stepwise
#/g4simple/setOutputOption eventwise

# Change the name of the output file (by default it's g4simple.[ext])
/analysis/setFileName detector_out_test

#/geometry/test/tolerance 0.01

# Steps are only written out if they are in a volume that matches a pattern set
# via the setVolID command
# Example setting a full volume name (exact match):
///g4simple/setVolID Crystal_PV 1
# Example using a regular expression to match multiple volumes, extract an
# integer from the name, and set it as the volID
#/g4simple/setVolID .*Detector([0-9]*).* $1
# To get all steps in all volumes, comment out all setVolID commands (removes
# all volume IDs from output), or uncomment the following line to keep the
# volume IDs:
#/g4simple/recordAllSteps

/run/initialize

#/vis/open OGLIX
/vis/open HepRepXML
/vis/scene/create g4simple_test
/vis/viewer/set/autoRefresh false
/vis/sceneHandler/attach
/vis/scene/add/volume world
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/add/axes 0 0 0 50 cm

#/vis/filtering/trajectories/create/chargeFilter
#/vis/filtering/trajectories/chargeFilter-0/add 0

#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma

/vis/modeling/trajectories/create/drawByAttribute
/vis/modeling/trajectories/select drawByAttribute-0
/vis/modeling/trajectories/drawByAttribute-0/verbose false
/vis/modeling/trajectories/drawByAttribute-0/setAttribute IMag

/vis/modeling/trajectories/drawByAttribute-0/addInterval green 0 keV 450 keV
/vis/modeling/trajectories/drawByAttribute-0/addInterval red 450 keV 650 keV
/vis/modeling/trajectories/drawByAttribute-0/addInterval cyan 650 keV 800 keV
/vis/modeling/trajectories/drawByAttribute-0/addInterval violet 800 keV 1000 keV
/vis/modeling/trajectories/drawByAttribute-0/addInterval orange 1000 keV 2000 keV
/vis/modeling/trajectories/drawByAttribute-0/addInterval blu 2000 keV 2500 keV
/vis/modeling/trajectories/drawByAttribute-0/addInterval yellow 2500 keV 2700 keV
/vis/modeling/trajectories/drawByAttribute-0/addInterval magenta 2700 keV 7000 keV

/vis/modeling/trajectories/drawByAttribute-0/green/setLineColourRGBA  0.00 1.00 0.00 1
/vis/modeling/trajectories/drawByAttribute-0/red/setLineColourRGBA  1.00 0.00 0.00 1
/vis/modeling/trajectories/drawByAttribute-0/cyan/setLineColourRGBA  0.00 1.00 1.00 1
/vis/modeling/trajectories/drawByAttribute-0/violet/setLineColourRGBA  0.70 0.43 0.86 1
/vis/modeling/trajectories/drawByAttribute-0/orange/setLineColourRGBA  1.00 0.65 1.00 1
/vis/modeling/trajectories/drawByAttribute-0/blu/setLineColourRGBA  0.00 0.00 1.00 1
/vis/modeling/trajectories/drawByAttribute-0/yellow/setLineColourRGBA  1.00 1.00 0.00 1
/vis/modeling/trajectories/drawByAttribute-0/magenta/setLineColourRGBA  1.00 0.00 1.00 1

# If you want to see the list of available NIST materials (e.g. to help you
# build your gdml file) uncomment this line
#/material/nist/listMaterials

# If you want to see the list of all physical volume names (e.g. to set volume
# IDs above) uncomment this line
/g4simple/listPhysVols

# Set up gps after /run/initialize
/gps/particle geantino
/gps/position 0 0 -800 cm
/gps/pos/type Point
#/gps/pos/confine Source_PV
/gps/ene/mono 2612 keV
/gps/direction 0 0 1
#/gps/ang/type iso

#/gps/particle  ion
#/gps/ion       83 212 0 0
#/gps/energy    0 MeV
#/grdm/nucleusLimits      208 212 81 83
#/gps/pos/type Volume
#/gps/pos/shape Sphere
#/gps/pos/radius 1 mm
#/gps/pos/centre 0 0 -5 # mm 
#/gps/pos/confine Source_PV


/vis/scene/endOfEventAction accumulate 1
/run/beamOn 1
/vis/viewer/flush
/vis/viewer/set/autoRefresh true

