#!/bin/bash
#
# USAGE: qsub run-g4simple.qsub run_detector_bi.mac
#
#$ -P short ### queue
#$ -j y     ### have logoutput and erroroutput in the same file
#$ -o /dev/null
#$ -e /dev/null

LOGFILE=$(echo $1 | cut -f 1 -d '.').out
source /lfs/l1/gerda/gerda-simulations/sw-containers/load-env.sh
cd "/lfs/l1/legend/users/bianca/IC_geometry/IC-legend/macro/"
g4simple $1 &> /lfs/l1/legend/users/bianca/IC_geometry/IC-legend/macro/output/$LOGFILE
